### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by blavejr** [blavejr/OrganiseDesktop#1]
If anyone could help with adding a simple GUI that would be great, something with tkinter maybe, I don't know you have freedom to do anything.

**Comment by curiousjazz77** [comment]
Quick question - Are there certain things you'd like to GUI to do and where would you like its placement? How would it interact with your existing code?

**Comment by blavejr** [comment]
I don't really have a plan, but I was thinking there can be one button to run the main script and maybe a few others for settings etc, but I was thinking of a design with one main button, but you are again free to do anything you like., What do you plan to make the Gui with? TKinter?

**Comment by rafimatchen** [comment]
Hi,
I could have a go at it with TKinter.

**Comment by blavejr** [comment]
Sure, not a problem. have fun :)

**Comment by mitrakic** [comment]
Is this issue still on going? I have some experience with TKinter (There's a Calculator project on my profile that I used it in) and I would love to give this a go.

**Comment by blavejr** [comment]
Hey @mitrakic yeah its still going on, have a crack at it. We need all the help we can get. Have fun :)

**Comment by mitrakic** [comment]
Hey, I added a GUI with one basic "Run" button, and fixed a couple bugs I saw in the setup and clean files. When you talked about other buttons for settings, what kind of settings were you referring to? Please take a look at what I have so far and let me know if you want me to add any other functionality or change anything.

**Comment by VoxelBuster** [comment]
Created a pull request with code for this issue

**Comment by son-vyas** [comment]
Hey @mitrakic , I have some experience in TKinter, can I help in any way. Please let me know.
