### ISSUE TITLE
Add more extentions

### ISSUE THREAD

**Issue by blavejr** [blavejr/OrganiseDesktop#2]
I dont know all the extensions out there so if anyone would like to take the time to search for and add extensions that would be super :)

**Comment by curiousjazz77** [comment]
Hi! 
I'm new to the open source community! Nice to e-meet you! I added in more extensions. Let me know what you think.

**Comment by blavejr** [comment]
Hi @curiousjazz77 thanks for taking interest in my little project, I hope you hate messy desktops as much as I do.

The code looks great, I will merge it. I didn't even know there were so many extensions. great Job :)

**Comment by curiousjazz77** [comment]
You're welcome. If you think any are missing, let me know! : )
I'm also looking through the code to check out your GUI issue.

**Comment by Krazune** [comment]
I added some extensions, and removed some duplicates.

**Comment by Sudhanshu36** [comment]
Hello, I've added some extensions that i knew. Also maybe we can make a separate folder for the extensions that are usually malware. I don't know how to make a separate section for this so it would be great if you can make an empty section for such extensions and then ping me so i can add them. :)

**Comment by blavejr** [comment]
@Sudhanshu36 send in a PR request.
