### ISSUE TITLE
Add a new file with all the extensions

### ISSUE THREAD

**Issue by TheWindRider** [blavejr/OrganiseDesktop#22]
I don't think it's a good practice to put several super-long lists of extensions in the same .py file as the main body of the program. 
One side-effect is that `programming_languages_extensions` are assigned value twice but was overlooked.  I don't know if these 2 values are exactly the same, but either way it's not reader-friendly. 

How about **a new JSON file to store all lists of extensions**? It could be edited manually to add more extensions, and could also be read by `Clean.py`

**Comment by blavejr** [comment]
@TheWindRider this is a brilliant idea, would you like to add this please? We would be very grateful.

**Comment by TheWindRider** [comment]
@blavejr Thanks for your reply, I will firstly create a JSON file with extensions, and make a PR.  Later I will make changes to `Clean.py` to read from this JSON file.  That will be another PR and I'll take some time and be a little more cautious.
