### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by DragosDumitrache** [blavejr/OrganiseDesktop#28]
Mind if I refactor some of the code while also offering support for terminal based functionality?

Happy to talk some more about some of the changes I had in mind

**Comment by blavejr** [comment]
Yeah, that would be great. Please make as many changes as you like and send a PR with a log of what you changed.

**Comment by DragosDumitrache** [comment]
Awesome. Is there a Gitter/Slack channel or anything where one might ask questions? I couldn't get it to run locally yet due to various errors, do you have a more comprehensive setup guide? Python version, requirements, etc? From the code, it seems like it's a GUI application, right? Since there's no support for OSX yet, I was also thinking of adding that and starting it as a command line app first, before worrying about the UI.

I have a lot of other questions bubbling, but for the time being, the ones above would give me enough information.

**Comment by blavejr** [comment]
Hi @DragosDumitrache I am really sorry for taking so long to reply to this message, I have just set up the slack channel. here is an invite link, please please please drop in and share your thoughts and help build.
https://join.slack.com/t/organisedesktop/shared_invite/enQtMzA2NTI2MTI0MzY4LWRlOWRjOGM0YTJmYjFiZGU3ZTUzM2M0MTA2N2U3MzljMmFhNGIyODlmZDg2N2E1Y2EwOWFiZjcxMzYzYjcyMTk
