### ISSUE TITLE
Add a better CONTRIBUTING.md

### ISSUE THREAD

**Issue by josuablejeru** [blavejr/OrganiseDesktop#48]
A Slack Cannel is fine... but a nice ``CONTRIBUTING.md`` with some clear rules will help this project a lot 😄

**Comment by blavejr** [comment]
@GreenMoon4 great idea, do you want to create that boilerplate and then we could add more rules etc as time goes

**Comment by sshah98** [comment]
I can do this too @blavejr. I'll submit a pull request once I fix the `CONTRIBUBTING.md`
