### ISSUE TITLE
No Coding standart

### ISSUE THREAD

**Issue by josuablejeru** [blavejr/OrganiseDesktop#50]
We have to add a Coding style to this project. :bowtie: 
Most variables are not camelcase ore use "_" for the legibility.

> We should follow [PEP8](https://www.python.org/dev/peps/pep-0008/) and [PEP257](https://legacy.python.org/dev/peps/pep-0257/#id12) to write better software together.

**Comment by katzaz10** [comment]
I would be happy to go through and touch up all the variable names to fit a standard

**Comment by blavejr** [comment]
Hey @josuablejeru thank you for bringing this up it is very important indeed.
@katzaz10 Please do it, it will be very highly appreciated :)

**Comment by GowthamPrakaash** [comment]
Hi @blavejr, 
I thought of some code fixes. Can I work on it?

**Comment by blavejr** [comment]
@GowthamPrakaash go right ahead man.
