### ISSUE TITLE
Remove folders that is empty.

### ISSUE THREAD

**Issue by KokoseiJ** [blavejr/OrganiseDesktop#78]
Sorry for the bad English if it's hard to understand.

I tested this program in my machine, It creates all of the folders in the list even if It won't have any files inside.

example) I don't have any CAD related files on my desktop, but this program still creates CAD folder which is empty and unnecessary.

also, Wouldn't it be great if it can also remove empty folders in the desktop?

So, my suggestion is:
1. Remove folders that is created by this program but doesn't have any files inside (or just don't create them in the first place)
2. Make a new option to remove empty folders in the desktop.

**Comment by Sudipt-panda** [comment]
Is anyone working on this? If not can I start working on this?
Thanks in advance

**Comment by KokoseiJ** [comment]
@Sudipt-panda Go ahead, I'm not even sure if @blavejr is still maintaining this project.

option 1 was done by PR #79 , You can start working on option 2.

also, We should consider fork this repo and start maintaining on our own, as it seems like the owner of this project doesn't really care about this anymore

**Comment by kashishlubana** [comment]
@KokoseiJ  The second option has been taken care of by our team and I will generate a pull request for the same soon.

**Comment by KokoseiJ** [comment]
Aight, so thanks to @kashishlubana this is finished. I will close this issue.

**Comment by kashishlubana** [comment]
@KokoseiJ and @blavejr , Thank you for letting me collaborate.
