### ISSUE TITLE
setup.py is missing README.rst during installation

### ISSUE THREAD

**Issue by nicolehli** [blavejr/OrganiseDesktop#8]
I followed the README.md instructions and ran ```python setup.py install```. The file requires a README.rst that is missing. What is this file and how to generate it?

**Comment by blavejr** [comment]
Hi @nicolehli, I am not sure what this file is. The setup.py file isn't really needed just run the script with python. I put the setup there so I dont forget to add a setup later. I will start working on that.

But if you run the Clean.py script it should work fine.
Thanks for your input :)

**Comment by nicolehli** [comment]
Thanks, i'll look at clean.py; it ran, haven't checked files yet.
