### ISSUE TITLE
Better way to locate special folders (Desktop, Public Desktop)

### ISSUE THREAD

**Issue by dvesic** [blavejr/OrganiseDesktop#9]
Hello.

While original way of getting special folders will work in great deal of cases, if there is localized version of Windows or older one - it will fail. This is more standardized way to find out user and Public Desktop folders.

So, if you do not mind, I would create pull request (code is already ready) for this.

Regards,
Dejan

**Comment by blavejr** [comment]
Hi @dvesic thanks a lot for your input, it is very much appreciated. put in a PR and I will review and accept. :)

**Comment by dvesic** [comment]
Already done :-)

Regards,
Dejan
