### ISSUE TITLE
Support installing as a python package

### ISSUE THREAD

**Issue by chaps** [blavejr/OrganiseDesktop#91]
Currently, the project contains python scripts but lacks a setup.py file at the root of the project in order to enable 
being able to install the sources as a python package e.g. (pip install ./)

Installing as a python package also includes handling console_scripts , which enables calling the organise_desktop as a cli command after installing it.

Other benefits include shipping and distributing the sources over pypi.

**Comment by chaps** [comment]
The following PR is a take at setting up the setup.py file so that it can be installed as a python package:

https://github.com/blavejr/OrganiseDesktop/pull/90

- enables the `organise_desktop` cli command
- enables calling the gui from `python -m organise_desktop`

**Comment by KokoseiJ** [comment]
Sorry for the late reply. I'm checking the code- I'll accept the code ASAP.

**Comment by chaps** [comment]
PR for issue was reviewed and accepted; closing issue.
